---
apiVersion: v1
kind: Template
labels:
  template: slave-image-wendy-template
metadata:
  annotations:
    description: |-
      Jenkins service, with persistent storage.
      You must have persistent volumes available in your cluster to use this template.
    iconClass: icon-jenkins
    tags: jenkins
  name: slave-image-wendy
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${JENKINS_SERVICE_NAME}-${IMAGE_NAME}
    annotations:
        slave-label: ${SLAVE_LABEL}
    labels:
      role: jenkins-slave
    spec:
      dockerImageRepository: "docker.io/fhwendy/${IMAGE_NAME}"


parameters:
- description: The name of the repository branch to reference in the configuration
  displayName: Branch
  name: IMAGE_NAME
- description: The name of the OpenShift Service exposed for the Jenkins container.
  displayName: Jenkins Service Name
  name: JENKINS_SERVICE_NAME
  value: jenkins
- description: The label
  name: SLAVE_LABEL
